In [2]:

%pip install -q numpy

import numpy as np

def generate_data(n=10):
    x = []
    y = []
    
    for _ in range(n):
        voltage = np.random.normal(220, 5)
        current = np.random.normal(10, 2)
        temperature = np.random.normal(40, 5)
        speed = np.random.normal(1500, 50)
        label = 1 if (voltage < 210 or voltage > 230 or current > 14 or temperature > 60) else 0
        
        x.append([voltage, current, temperature, speed])
        y.append(label)
    
    return np.array(x), np.array(y)
        
X, y = generate_data()

print("Data & Labels:\n")

for i in range(len(X)):
    label_text = "1" if y[i] == 1 else "0"
    print(f"{X[i]} → {label_text}")

Note: you may need to restart the kernel to use updated packages.
Data & Labels:

[ 226.05260586   10.35040938   43.32979293 1493.24283284] → 0
[ 219.39924595   10.4197525    40.2774856  1523.25902294] → 0
[ 217.02764105   10.8646602    39.3245331  1606.56511424] → 0
[ 218.50511156    7.42724364   40.96528211 1485.00090019] → 0
[ 233.70508238   10.4729315    42.65857075 1422.36570268] → 1
[ 216.37850078   10.65626143   40.55005355 1561.9166965 ] → 0
[ 209.42627854   11.25974189   39.71878909 1502.72671348] → 1
[ 226.04290213    9.95539085   40.79176435 1473.33614794] → 0
[ 230.02401564    7.73543357   40.18930135 1454.54935838] → 1
[ 223.83159986   12.81421156   37.01958455 1470.15572216] → 0



[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: C:\Users\Daniel Olatunji\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [ ]:
#Data normalization
# BEFORE normalization
X = X/X.max(axis=0)
print(X)